debug: False

wandb:
  project: vqvae-mnist
  name: None
  log_embeddings: True
  log_latent_projections: True

model:
  encoder:
    z_dim: ${model.vq.embedding_dim}
    leaky_relu_negative_slope: 0.125
    dropout_p: 0.18
  decoder:
    z_dim: ${model.vq.embedding_dim}
    leaky_relu_negative_slope: ${model.encoder.leaky_relu_negative_slope}
    dropout_p: ${model.encoder.dropout_p}
  vq:
    embedding_dim: 8
    num_embeddings: 128
    commitment_cost: 0.22
    decay: 0.99
  optimizer:
    learning_rate: 0.003

training:
  batch_size: 1024
  num_epochs: 100